/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "matrix.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
matrix_operations_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		matrices matrix_add_1_arg;
		matrices matrix_multiply_1_arg;
		matrix matrix_inverse_1_arg;
		matrix matrix_transpose_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case MATRIX_ADD:
		_xdr_argument = (xdrproc_t) xdr_matrices;
		_xdr_result = (xdrproc_t) xdr_matrix;
		local = (char *(*)(char *, struct svc_req *)) matrix_add_1_svc;
		break;

	case MATRIX_MULTIPLY:
		_xdr_argument = (xdrproc_t) xdr_matrices;
		_xdr_result = (xdrproc_t) xdr_matrix;
		local = (char *(*)(char *, struct svc_req *)) matrix_multiply_1_svc;
		break;

	case MATRIX_INVERSE:
		_xdr_argument = (xdrproc_t) xdr_matrix;
		_xdr_result = (xdrproc_t) xdr_matrixInverse;
		local = (char *(*)(char *, struct svc_req *)) matrix_inverse_1_svc;
		break;

	case MATRIX_TRANSPOSE:
		_xdr_argument = (xdrproc_t) xdr_matrix;
		_xdr_result = (xdrproc_t) xdr_matrix;
		local = (char *(*)(char *, struct svc_req *)) matrix_transpose_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (MATRIX_OPERATIONS_PROG, MATRIX_OPERATIONS_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MATRIX_OPERATIONS_PROG, MATRIX_OPERATIONS_VERS, matrix_operations_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MATRIX_OPERATIONS_PROG, MATRIX_OPERATIONS_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MATRIX_OPERATIONS_PROG, MATRIX_OPERATIONS_VERS, matrix_operations_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MATRIX_OPERATIONS_PROG, MATRIX_OPERATIONS_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
