/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "matrix.h"

bool_t
xdr_matrices (XDR *xdrs, matrices *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (4 +  100  + 100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->row1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->col1))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->a, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->row2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->col2))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->b, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->row1);
			IXDR_PUT_LONG(buf, objp->col1);
			{
				register int *genp;

				for (i = 0, genp = objp->a;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->row2);
			IXDR_PUT_LONG(buf, objp->col2);
			{
				register int *genp;

				for (i = 0, genp = objp->b;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (4 +  100  + 100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->row1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->col1))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->a, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->row2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->col2))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->b, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->row1 = IXDR_GET_LONG(buf);
			objp->col1 = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->a;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->row2 = IXDR_GET_LONG(buf);
			objp->col2 = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->b;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->row1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->col1))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->a, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->row2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->col2))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->b, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matrix (XDR *xdrs, matrix *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (2 +  100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->row))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->col))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->a, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->row);
			IXDR_PUT_LONG(buf, objp->col);
			{
				register int *genp;

				for (i = 0, genp = objp->a;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (2 +  100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->row))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->col))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->a, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->row = IXDR_GET_LONG(buf);
			objp->col = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->a;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->row))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->col))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->a, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matrixInverse (XDR *xdrs, matrixInverse *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->row))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->col))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->a, 100,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->flag))
		 return FALSE;
	return TRUE;
}
